name: Run Tests

on: [push, pull_request]


jobs:
  e2e:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: voorhoede/get-netlify-url@v2
        id: get-netlify-url
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo ${{ steps.get-netlify-url.outputs.url }}
          echo "preview url: $steps.get-netlify-url.outputs.url"
        