name: Run Tests

on: [push, pull_request]


jobs:
  e2e:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: voorhoede/get-netlify-url@v2
        id: get-netlify-url
      - uses: cypress-io/github-action@v1
        env:
          CYPRESS_BASE_URL: ${{ steps.get-netlify-url.outputs.url }}
        with:
          wait-on: ${{ steps.get-netlify-url.outputs.url }}