name: Run Tests

on: [pull_request]


jobs:
  e2e:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # get netlify preview URL
    - uses: voorhoede/get-netlify-url@v2
      id: get-netlify-url
    # start node scripts
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x' 
    - uses: pnpm/action-setup@v2
      with:
        version: 'latest'     
    - name: Clean install dependencies
      run: pnpm install
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run your tests
      run: pnpm run test
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ steps.get-netlify-url.outputs.url }}
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report
